repos:
  - repo: https://github.com/kynan/nbstripout # strip notebooks of content
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/psf/black # autoformat code
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8 # linting, that is check for formatting
    rev: 4.0.1 
    hooks:
      - id: flake8
  #- repo: https://github.com/s-weigand/flake8-nb # linting for notebooks
  #  rev: v0.3.1 
  #  hooks:
  #    - id: flake8-nb